apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: fastapi-api-key
  namespace: production
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: fastapi-secret
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: fastapi/api_key2
        property: API_KEY 