# Development values for FastAPI app
replicaCount: 3
image:
  repository: 579177902857.dkr.ecr.us-east-1.amazonaws.com/fastapi-app
  tag: latest
  pullPolicy: Always
  name: 579177902857.dkr.ecr.us-east-1.amazonaws.com/fastapi-app:latest
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080
env:
  LOG_LEVEL: "INFO"
serviceAccount:
  create: true
  name: fastapi-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::579177902857:role/fastapi-sa-role

livenessProbe:
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3 