replicaCount: 2
image:
  repository: fastapi-app
  tag: latest
  pullPolicy: Always
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  type: ClusterIP
  port: 80
env:
  LOG_LEVEL: "INFO"
serviceAccount:
  name: fastapi-sa
  namespace: production
  roleArn: arn:aws:iam::<TU_AWS_ACCOUNT_ID>:role/fastapi-sa-role 