# Development values for FastAPI app
replicaCount: 1
image:
  repository: fastapi-app
  tag: dev
  pullPolicy: Always
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
service:
  type: ClusterIP
  port: 80
env:
  LOG_LEVEL: "DEBUG"
serviceAccount:
  name: fastapi-sa
  namespace: development
  roleArn: arn:aws:iam::579177902857:role/fastapi-sa-role 