replicaCount: 2
image:
  repository: fastapi-app
  tag: "latest"
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
service:
  type: ClusterIP
  port: 80
env:
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"
serviceAccount:
  name: fastapi-sa
  namespace: production
  roleArn: arn:aws:iam::579177902857:role/fastapi-sa-role

livenessProbe:
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3 